on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.22", "1.23"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Test with the Go CLI
        run: go test

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
